#!/bin/bash

output_dir="$(realpath $(dirname $0))"
    docker run --rm -v ${output_dir}:/go/bin golang:1.11 sh -c "
        set -o errexit
        set -o xtrace

        cd /go
        go get github.com/rlmcpherson/s3gof3r/gof3r
        go get github.com/minio/mc
    "
