apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: {{ template "percona.fullname" . }}
  labels:
    app: {{ template "percona.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  serviceName: {{ template "percona.fullname" . }}
  replicas: 1
  updateStrategy: 
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ template "percona.fullname" . }}
      component: pmm
  template:
    metadata:
      labels:
        app: {{ template "percona.fullname" . }}
        component: pmm
    spec:
      securityContext:
        supplementalGroups: [1000]
{{ if eq .Values.platform "kubernetes" }}
        fsGroup: 1000
{{ end }}
      containers:
        - name: {{ template "percona.fullname" . }}
          image: "{{ .Values.imageRepo }}:{{ .Values.imageTag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
          resources:
{{ toYaml .Values.resources | indent 12 }}

          ports:
            - name: https
              protocol: TCP
              containerPort: 443
          volumeMounts:
            - name: pmmdata
              mountPath: /pmmdata

          env:
            - name: DISABLE_UPDATES
              value: "true"

            - name: METRICS_RESOLUTION
              value: "1s"

            - name: METRICS_RETENTION
              value: "720h"

            - name: QUERIES_RETENTION
              value: "8"

            - name: METRICS_MEMORY
              value: "600000"
      {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: pmmdata
    spec:
      accessModes: [ {{ .Values.persistence.accessMode | quote }} ]
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
      {{- else }}
      volumes:
      - name: pmmdata
        hostPath:
          path: "/mnt/disks/ssd0"
      {{- end -}}
